### ISSUE TITLE
error: pathspec '...' did not match any file(s) known to git

### ISSUE THREAD

**Issue by Dauflo** [stefanzweifel/git-auto-commit-action#6] opened 2019-09-19 12:59 UTC
Hi,

I was trying your github action for a personnal project and end up with that stack trace

```
Run stefanzweifel/git-auto-commit-action@v2.0.0
/usr/bin/docker run --name bb812c55c43200fd4a7694090566760cb690_af6ffa --label 04bb81 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_COMMIT_AUTHOR_EMAIL -e INPUT_COMMIT_AUTHOR_NAME -e INPUT_COMMIT_MESSAGE -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/git-action-playground-v2/git-action-playground-v2":"/github/workspace" 04bb81:2c55c43200fd4a7694090566760cb690
Checking for uncommitted changes in the git working tree.
error: pathspec '2/merge' did not match any file(s) known to git
##[error]Docker run failed with exit code 1
```

I searched a bit for this error, and it seems that maybe git does not know the branch i'm trying to checkout (https://stackoverflow.com/questions/5989592/git-cannot-checkout-branch-error-pathspec-did-not-match-any-files-kn)

I think the trick is maybe to add `git fetch` to your `entrypoint.sh` to be sure git know all the branches

**Comment by stefanzweifel** [comment] 2019-09-19 13:27
Hi 👋

That might be a good idea, yeah. Would it be possible for you, to fork this project, make the change in `entrypoint.sh` and use it with your Action?

You would have to update your code to:

```diff
-- uses: stefanzweifel/git-auto-commit-action@v2.0.0
+- uses: Dauflo/git-auto-commit-action@master
  with:
    commit_author_email: john.doe@example.com
    commit_author_name: John Doe
    commit_message: Apply automatic changes
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This might also be related to actions/checkout#6. Most of the problems with this action are related to how GitHub checkouts the code.

**Comment by TingluoHuang** [comment] 2019-09-20 03:02
`error: pathspec '2/merge' did not match any file(s) known to git` means you are on a PR merge ref. What behavior do you want when your action running in a PR run? @stefanzweifel

**Comment by stefanzweifel** [comment] 2019-09-20 06:21
@TingluoHuang The action should just commit and push changes back to the branch, where the action is being run on. If it's a PR from another person, the changes should be pushed back to their repo (if this is even possible).

I've followed the discussion in actions/checkout#6, as I too had issues where the repo was in a detached state and therefore couldn't commit back to the repo.

I've used `git checkout "${GITHUB_REF:11}"` to checkout the branch, but looks like this breaks the action with PRs.
Will try this approach over the next few days to get to checkout the right branch https://github.com/elstudio/actions-js-build/blob/41d604d6e73d632e22eac40df8cc69b5added04b/commit/entrypoint.sh#L48

**Comment by Dauflo** [comment] 2019-09-20 08:01
@stefanzweifel Hi, the `git checkout "{GITHUB_REF:11}"` is on of the problem, the `:11` truncate too much the reference of the branch.
I've removed the checkout line, and now i'm struggling on the `git push`, I'm trying to find which is the good upstream variable for the git push. Hope that can help you a bit

**Comment by stefanzweifel** [comment] 2019-09-20 08:18
Yeah I see that too. Wanted to use my own action in a project and ran in the same problem.

I'm trying to get it working again on a branch. Here's the current state of the `entrypoint.sh` file.
https://github.com/stefanzweifel/git-auto-commit-action/blob/fix-branch-checkout/entrypoint.sh

I'm also using the `ref`-argument in my project:

```
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
```

Will come back to this issue, when I got a working solution.

**Comment by Dauflo** [comment] 2019-09-20 09:10
Congratz @stefanzweifel, the action now work perfectly !

If you want the logs just in case :

```
Run Dauflo/git-auto-commit-action@v2.0.1
/usr/bin/docker run --name bb81da6a5c78d7e1483d8c6e8040c9e7bafe_27d99e --label 04bb81 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_COMMIT_AUTHOR_EMAIL -e INPUT_COMMIT_AUTHOR_NAME -e INPUT_COMMIT_MESSAGE -e INPUT_REF -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/git-action-playground-v2/git-action-playground-v2":"/github/workspace" 04bb81:da6a5c78d7e1483d8c6e8040c9e7bafe
Checking for uncommitted changes in the git working tree.
INPUT_REF value: feat/test-pep
Previous HEAD position was 59bd61e Merge 03e494e163093025d14bfacf51c7a0fe58857611 into 1223aa3a5420f4cf6194ee1c25f824fcc31c1bb1
M	my_app/core/math.py
M	tests/test_math.py
Branch 'feat/test-pep' set up to track remote branch 'feat/test-pep' from 'origin'.
Switched to a new branch 'feat/test-pep'
[feat/test-pep f10f80d] Apply PEP8 changes
 Author: Dauflo <284994@supinfo.com>
 2 files changed, 4 insertions(+), 2 deletions(-)
To https://github.com/Dauflo/git-action-playground-v2
   03e494e..f10f80d  HEAD -> feat/test-pep
Branch 'feat/test-pep' set up to track remote branch 'feat/test-pep' from 'origin'.
```

**Comment by stefanzweifel** [comment] 2019-09-20 09:29
Thanks for the quick feedback. Will tag a new stable release very soon.

**Comment by stefanzweifel** [comment] 2019-09-20 19:26
[v2.1.0](https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v2.1.0) has been tagged. Going to close this issue now.

@Dauflo I've renamed the `ref`-argument to `branch` to be more clear.

**Closed by stefanzweifel** 2019-09-20 19:26 UTC

**Comment by EfficientSetting** [comment] 2020-05-20 22:04
Hey @stefanzweifel,
I'm using v4 of your great GH action and still seeing the same issue. 

What I'm trying to do is to run this action on a PR, I'm using actions/checkout@v2 with no parameters and I've set `branch: ${{ github.head_ref }}`

Any idea why this is still happening?

**Comment by ziming** [comment] 2020-07-05 11:37
I'm having the same problem too.

Here is my code

```
-   name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Fix styling
            branch: ${{ steps.extract_branch.outputs.branch }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by stefanzweifel** [comment] 2020-07-05 16:17
@ziming 

1. On what event is your workflow listening to? 
2. What‘s the value of „ ${{ steps.extract_branch.outputs.branch }}“? If it‘s empty or a branch name that doesn‘t exist, the Action will fail
3. Which version of „actions/checkout“ are you using? V1 or v2?

The issue has been fixed over a year ago, and the way the Action switches to a branch has been battle tested over the last few months.

**Comment by pablosjv** [comment] 2021-02-19 10:12
I came across the same issue using the latest version: `stefanzweifel/git-auto-commit-action@v4.8.0`

My problem was setting the parameter `branch: maser` giving me the following error

```console
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.8.0/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: master
error: pathspec 'master' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.8.0/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.8.0/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

When I removed the parameter it worked. Maybe this is just for the master branch?

**Comment by stefanzweifel** [comment] 2021-02-19 13:35
@pablosjv Thanks for reporting! Could you share your workflow file here or in a new issue? 

I honestly can't remember what all the causes for the original problem were and I think a fresh issue for a more recent version of the Action would be better, instead of piling onto this reatively old issue.

**Comment by pablosjv** [comment] 2021-02-20 16:01
Thanks @stefanzweifel. I have created the issue #141 to track the error.
