### ISSUE TITLE
"nothing to commit" error when there is LF/CRLF changes

### ISSUE THREAD

**Issue by ZeroRin** [stefanzweifel/git-auto-commit-action#241] opened 2022-09-10 13:10 UTC
**Version of the Action**
`v4.x.x`

**Describe the bug**
When a file's line break is changed (CRLF->LF or LF->CRLF), running `git status` will result in an untracked modification (which passes the dirty check of this action).
However, if `core.autocrlf` is set to `true` or `input`, after running `git add` the change will be fixed and running `git status` or `git commit` after that will give you `nothing to commit, working tree clean`. As a result, the commit step would raise a "nothing to commit" error.

In my own case, I fixed the issue by running `_switch_to_branch` and `_add_files` before `_git_is_dirty`, but I'm not sure whether there will be other subsequences.

**Comment by stefanzweifel** [comment] 2022-09-17 14:03
I'm sure this bug is annoying, but this seems to be out of scope for this Action to solve.

I don't fully understand what you're doing or how exactly you're encountering this issue. I can't seem to reproduce this error on my macOS machine nor do I know how we should write tests for this.

I've added a note in the "Limitations & Gotchas" section of the README in https://github.com/stefanzweifel/git-auto-commit-action/commit/18870f2286c2860e1e6c802fe8f7d5f382b903d7, to inform others about this bug.

If you think this bug affects a lot of people and is worth fixing, please reopen this issue and provide an example project or step by step instructions on how to reproduce this error.

**Comment by stefanzweifel** [comment] 2022-09-19 07:51
Thanks @ZeroRin for taking the time to put this example repo together.
Will take some time this week to figure out, how we could add a test for this in the action and how we could solve this. Or if it's too much work for the action and is something that has to be solved in "userland".

**Comment by stefanzweifel** [comment] 2022-09-28 18:34
Thanks again @ZeroRin for providing a reproduction repository.
I was able to write a test to verify that git-auto-commit doesn't work as how you expect it to work: https://github.com/stefanzweifel/git-auto-commit-action/commit/b208f78c106ef46799e92c989427512a5259f056.

However, after investing 2-3 hours into this I was not able to make it work as you might need it. Setting `core.autocrlf` to `true`, `input` or `false` didn't have any effect. The changes in your fork also didn't yield any result.

Feel free to clone the repository, install the test suite with `yarn` or `npm install` and then run the test with `yarn test --filter "crlf"`. 
By switching `assert_line` and `refute_line` [here](https://github.com/stefanzweifel/git-auto-commit-action/blob/b208f78c106ef46799e92c989427512a5259f056/tests/git-auto-commit.bats#L953-L955) you would tell the test suite, that it would actually work.

If you find a fix, please open a PR.

---

For now I'm letting this issue rest. 
I deliberately put "for the 80% use case" in the description of this Action, so that I don't invest too much time fixing obscure or niche workflows (not offense).

**Closed** 2022-12-01 19:47 UTC
Labels: bug
