### ISSUE TITLE
action cannot be used with required status checks

### ISSUE THREAD

**Issue by dudicoco** [stefanzweifel/git-auto-commit-action#163] opened 2021-06-07 15:01 UTC
When using the action with a protected branch which has required status checks configured, once a commit is pushed back into the branch the required status checks hang:

![Screen Shot 2021-06-07 at 11 02 40](https://user-images.githubusercontent.com/51051860/121039515-d288f400-c7b9-11eb-9a49-766c3e95140e.png)

This is related to https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs

I assume the solution would be to use a PAT instead of the default github token as described in https://github.com/stefanzweifel/git-auto-commit-action/issues/38#issuecomment-580174859
However, triggering the jobs again is very time/money consuming, so a more elegant solution should be implemented.

**Comment by stefanzweifel** [comment] 2021-06-08 18:49
It's new to me, that workflows start to hang when a commit is pushed to a protected branch. Usually the commit can't even be made. 🤔
Will do some further testing, but are you 100% sure that the workflows hang because of the commit made? Or did GitHub maybe just had an outage or something other interfered? 

But you're probably right, that a PAT solves this problem. The default `GITHUB_TOKEN` has some strict permissions and can have a few side effects (like you mentioned).


> However, triggering the jobs again is very time/money consuming, so a more elegant solution should be implemented.

If you do not want to re-run workflows I would suggest adding if-guards to your workflows. In this comment from a past issue I shared an example: https://github.com/stefanzweifel/git-auto-commit-action/issues/87#issuecomment-691044617

Before running a job in a workflow, you check the actor which initiated the workflow run. If the actor is the same as the committer, the job should not run.

```yaml
name: My Workflow

on: push

jobs:
  my-workflow:

    # ↓ This condition is important
    if: github.actor != 'org-bot' 

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}

    # ...

    run: date > current-date.txt

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: My Commit Message
        branch: ${{ github.head_ref }}
        commit_user_name: org-bot
```

**Comment by dudicoco** [comment] 2021-06-13 14:56
@stefanzweifel i'm sure that the workflows hang because of the commit hang, and not because of anything else, i've tested it multiple times.
The `if` clause will not help here because it will prevent the workflow from rerunning - which will cause the status checks to hang.

I'm surprised that no one else brought this issue up so far, it's a pretty common scenario to have a protected branch with required status checks.

**Comment by stefanzweifel** [comment] 2021-06-26 13:43
Sorry for my late response to this issue @dudicoco . I've taken 2 weeks off of regular and open-source work. (Needed some time to refresh my mind)

I could reproduce this "error" in my test repository: https://github.com/stefanzweifel/git-auto-commit-action-demo-app.
The repo has [2 workflows](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/tree/main/.github/workflows):

- [`test.yml`](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/blob/main/.github/workflows/test.yml) which runs the apps test suite
- [`format_php.yml`](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/blob/main/.github/workflows/format_php.yml) to format the PHP code according to a defined standard (I'm a PHP guy, that's why I've used this)

The repo has been set up with a protection rule. The `test` status check has to pass before merging:

<img width="928" alt="Screenshot 2021-06-26 at 15 12 36" src="https://user-images.githubusercontent.com/1080923/123514062-f50f7e00-d690-11eb-8aec-0301d9baf9e6.png">


In [this PR](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/pull/28) I've made a change to the PHP code which triggered the `format_php` action. This resulted in the same problem you're describing at the beginning.

<img width="934" alt="Screenshot 2021-06-26 at 15 18 27" src="https://user-images.githubusercontent.com/1080923/123514165-c3e37d80-d691-11eb-94a0-29141a376fb0.png">

As you correctly identified, this is because of the restrictions GitHub made to `secrets.GITHUB_TOKEN`.

[Adding a personal access token](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/pull/28/commits/71e7883b36a882ea0370a36349c3e590e0d2a7da) resolves this issue, as now the required `test`-workflow is being triggered, after my `format_php`-workflows pushes a commit to the branch.

<img width="935" alt="Screenshot 2021-06-26 at 15 24 12" src="https://user-images.githubusercontent.com/1080923/123514293-91865000-d692-11eb-93e4-c30b08eb7f14.png">

> The if clause will not help here because it will prevent the workflow from rerunning - which will cause the status checks to hang.

You're right. A `if`-statement on the job level wouldn't help here as by the protection rule definition the `test`-workflow/job has to run.

However, you could add `if`-statements to the steps in a workflow to check, if the `git.actor` which created the commit was a bot. This way you could skip the steps which are taking a long time to run. Such a step could look like this:

```yaml
-   name: Step that takes a long time to run
    if: ${{ github.actor != 'my-org-bot' }}
    run: /path/to/bin
``` 

It's definitely not elegant and can be very tedious if you have many steps in your workflow, but we are all constraint by the way how GitHub Actions work.

> so a more elegant solution should be implemented.

That would be great, but that's basically impossible. I don't work for GitHub and don't have leverage to change anything. `git-auto-commit` is _just_ a simple bash script that runs 5 `git`-commands. It doesn't even interact with the GitHub API.

The base problem is:

- Protection rule requires status check to pass.
- Commit made by a regular user triggers run for status check.
- Commit made by `git-auto-commit` does not trigger run for status check.
- Using a PAT triggers run for status check, but by doing so, the same work is basically done twice.

I'm closing this issue now, as I don't see a practical way to solve this problem. If you have found a solution to this problem, feel free to submit a PR or write your solution here. I'm sure a lot of people would be happy to read it.

**Closed by stefanzweifel** 2021-06-26 13:43 UTC
Labels: bug, enhancement

**Comment by dudicoco** [comment] 2021-07-05 08:45
Thank you for the elaborate reply @stefanzweifel!
